Pttb 23 frontend date edit in user friendly way there should not be edit button to save
proshore/TickerPRO-ProshoreTimeTrackingSystem-Frontend pull request #53
Opened 2022-09-01 11:39 UTC by Suryabogan

I have made success and error toast notification for timelog update and failure and also made the task user friendly. User can click outside edit box to save changes and click enter to save changes too

2022-09-02 05:38 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
> +          <td><input class="edit" type="text" v-model="log.end_time" @focusout="editLogs(log.activity_name, userId, log.project_id, log.billable, log.start_time, log.end_time, log.id)" @keyup.enter="
Instead of passing multiple arguments to "editLogs" function, just pass "log" object and destrcture in the "editLogs" function

2022-09-02 05:39 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
> +      $toast.success('Congratulations! Your Timelog updated successfully.');
$toast.success('Your Timelog updated successfully.');
 Remove "Congratulations!"

2022-09-02 05:54 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
> +            <input class="edit" type="text" v-model="log.activity_name" @focusout="editLogs(log.activity_name, userId, log.project_id, log.billable, log.start_time, log.end_time, log.id)" @keyup.ente
You are missing "data-cy" attirbute

2022-09-02 05:55 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
> +          <td><input class="edit" type="text" v-model="log.start_time" @focusout="editLogs(log.activity_name, userId, log.project_id, log.billable, log.start_time, log.end_time, log.id)" @keyup.enter
"data-cy" attribute is missing

2022-09-02 05:55 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
> +          <td><input class="edit" type="text" v-model="log.end_time" @focusout="editLogs(log.activity_name, userId, log.project_id, log.billable, log.start_time, log.end_time, log.id)" @keyup.enter="
"data-cy" attribute is missing

2022-09-02 08:00 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
>              <button type="button" class="btn btn-light btn-sm mx-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
Add "data-cy" attribute

2022-09-05 04:11 UTC, alex1the1great commented on src/modules/tracker/components/TrackerList.vue
>      var data = {
use "let" instead of "var"

2022-09-05 08:44 UTC, shrestharikesh requested changes
looks good

2022-09-05 08:49 UTC, merged